"""empty message

Revision ID: 02ef7dec6773
Revises: e2935261e530
Create Date: 2022-10-09 13:46:14.512765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02ef7dec6773"
down_revision = "e2935261e530"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cafe", sa.Column("kakao_cafe_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "cafe", ["kakao_cafe_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cafe", type_="unique")
    op.drop_column("cafe", "kakao_cafe_id")
    # ### end Alembic commands ###
