"""empty message

Revision ID: e2935261e530
Revises: 0002aee21f07
Create Date: 2022-09-18 13:54:29.093290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2935261e530"
down_revision = "0002aee21f07"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("login_id", sa.String(length=50), nullable=False))
    op.add_column("user", sa.Column("password", sa.String(length=128), nullable=False))
    op.add_column("user", sa.Column("nickname", sa.String(length=64), nullable=True))
    op.add_column("user", sa.Column("is_staff", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("authorizations", sa.JSON(), nullable=False))
    op.create_index(op.f("ix_user_login_id"), "user", ["login_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_login_id"), table_name="user")
    op.drop_column("user", "authorizations")
    op.drop_column("user", "is_staff")
    op.drop_column("user", "nickname")
    op.drop_column("user", "password")
    op.drop_column("user", "login_id")
    # ### end Alembic commands ###
