name: Build API and Deploy

on:
  push:
    branches:
      - "test/git-action-test-1"





jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Repo
        uses: actions/checkout@v2
      # Login to docker
      # This can be used for both Docker Hub and
      # GitHub container registry.
      - name: Login to NCP Registry
        uses: docker/login-action@v1
        with:
          # Remove the following line if you want to
          # login to docker hub
          registry: ${{ secrets.registry }}
          username: ${{ secrets.registry_user }}
          # secrets are GitHub actions that can be added
          # from settings of the repo.
          password: ${{ secrets.registry_password }}
      # Build the docker image and push it.
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.hub_name }}/fastapi-server:test



  #  Name of the job is deploy
  deploy:
    needs: example-job
    runs-on: ubuntu-latest
    steps:
      - name: Login to NCP Registry
        uses: docker/login-action@v1
        with:
          # Remove the following line if you want to
          # login to docker hub
          registry: ${{ secrets.registry }}
          username: ${{ secrets.registry_user }}
          # secrets are GitHub actions that can be added
          # from settings of the repo.
          password: ${{ secrets.registry_password }}
      # SSH into the server
      - name: executing remote ssh commands using ssh key
        run: |
          echo "${{ secrets.CA_PEM }}" > ca.pem
          echo "${{ secrets.CERT_PEM }}" > cert.pem
          echo "${{ secrets.KEY_PEM }}" > key.pem
          
          echo ENVIRONMENT="${{ secrets.ENVIRONMENT }}" >> .env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> .env
          echo DB_USER="${{ secrets.DB_USER }}" >> .env
          echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
          echo DB_NAME="${{ secrets.DB_NAME }}" >> .env
          echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
          echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
          echo JWT_ALGORITHM="${{ secrets.JWT_ALGORITHM }}" >> .env
          

          docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=${{ secrets.HOST }}:${{ secrets.PORT }} run --env-file .env ${{ secrets.hub_name }}/fastapi-server:test

        shell: bash
