name: Build API and Deploy

on:
  push:
    branches:
      - "develop"

jobs:
  checkout-code-build-image-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Repo
        uses: actions/checkout@v2
      # Login to docker
      # This can be used for both Docker Hub and
      # GitHub container registry.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          # Remove the following line if you want to
          # login to docker hub.
          username: ${{ secrets.docker_hub_username }}
          # secrets are GitHub actions that can be added
          # from settings of the repo.
          password: ${{ secrets.CR_PAT }}
      # Build the docker image and push it.
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ghcr.io/owner/fastapi_server:v1

  
  # Name of the job is deploy
  deploy:
    needs: checkout-code-build-image-job
    runs-on: ubuntu-latest
    steps:
      # SSH into the server
      # Login to docker
      # This can be used for both Docker Hub and
      # GitHub container registry.
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          # Remove the following line if you want to
          # login to docker hub.
          username: ${{ secrets.docker_hub_username }}
          # secrets are GitHub actions that can be added
          # from settings of the repo.
          password: ${{ secrets.CR_PAT }}
      
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          # The server IP of our VPS from DigitalOcean
          # or any other provider. This is again
          # passed in as a secret.
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          # Username of the user sshing into the server
          username: ${{ secrets.SERVER_USERNAME }}
          # The private ssh key in order to get access
          key: ${{ secrets.KEY }}
          script:  ${{ secrets.SERVER_PASSWORD }} && docker pull ghcr.io/owner/fastapi_server:v1 && docker run ghcr.io/owner/fastapi_server:v1
